apiVersion: v1
kind: Service
metadata:
  name: kohesio-frontend-service
  labels:
    app: kohesio-frontend-service
spec:
  type: NodePort
  ports:
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: kohesio-frontend-service